// ================================================================
// 🔒 CONFIGURACIÓN CSP (Content Security Policy)
// ================================================================

// Lista completa de dominios para CSP
export const cspDomains = [
  "'self'",
  "https://masitaprex.com",
  "https://accounts.google.com",
  "https://identitytoolkit.googleapis.com",
  "https://www.googleapis.com",
  "i.postimg.cc",
  "https://i.postimg.cc",
  "https://*.postimg.cc",
  "https://unpkg.com",
  "https://cdn.jsdelivr.net",
  "https://remixicon.com",
  "https://generativelanguage.googleapis.com",
  "https://fonts.googleapis.com",
  "https://fonts.gstatic.com",
  "https://cdnjs.cloudflare.com", 
  "https://cdn.tailwindcss.com",
  "https://cdn.jsdelivr.net", 
  "https://firestore.googleapis.com",
  "https://identitytoolkit.googleapis.com",
  "https://securetoken.googleapis.com",
  "https://firebase.googleapis.com",
  "https://www.googleapis.com",
  "https://auth.masitaprex.com",
  "https://peliprex-31wrsa.fly.dev",
  "https://cdn.plyr.io",
  "https://images.unsplash.com",
  "https://cdn.tailwindcss.com",
  "https://cdn.jsdelivr.net",
  "https://*.effectivegatecpm.com",
  "https://*.adsterra.com",
  "https://cdn.jsdelivr.net/npm/plyr@3.7.8/dist/plyr.css",
  "https://cdn.jsdelivr.net/npm/plyr@3.7.8/dist/plyr.js",
  "https://lh3.googleusercontent.com",
  "https://peliprex-pe-v2.fly.dev",
  "https://1.bp.blogspot.com",
  "https://www.masitaprex.com",
  "https://peliprex.fly.dev",
  "https://consulta-pe-abf99.firebaseapp.com",
  "https://consulta-pe-abf99.firebasestorage.app",
  "https://masitaprexv2.fly.dev",
  "https://cdn-icons-png.flaticon.com",
  "https://cdnjs.cloudflare.com",
  "https://fonts.googleapis.com",
  "https://fonts.gstatic.com",
  "https://unpkg.com",
  "https://api.masitaprex.com",
  "https://api.ipquery.io",
  "https://m.facebook.com",
  "https://youtube.com",
  "https://www.youtube.com",
  "https://wa.me",
  "https://www.gstatic.com",
  "https://blogger.googleusercontent.com",
  "https://via.placeholder.com",
  "https://image.tmdb.org",
  "https://apis.google.com",
  "https://firebase.googleapis.com",
  "https://firestore.googleapis.com",
  "https://securetoken.googleapis.com",
  "https://drive.google.com",
  "https://generativelanguage.googleapis.com",
  "https://sdk.mercadopago.com",
  "https://mercadopago.com",
  "https://api.mercadopago.com",
  "https://www.mercadopago.com.pe",
  "https://www.mercadopago.com",
  "https://pago.mercadopago.com.pe",
  "https://http2.mlstatic.com",
  "https://*.mercadopago.com",
  "https://*.mercadolibre.com",
  "https://www.appcreator24.com",
  "https://img.utdstc.com",
  "https://com-masitaorex.uptodown.com",
  "https://stc.utdstc.com",
  "https://apk.e-droid.net",
  "https://apkpure.com",
  "https://placehold.co",
  "https://www.google.com",
  "https://google.com",
  "https://github.com",
  "https://www.github.com",
  "https://api.github.com",
  "https://www.facebook.com",
  "data:",
  "blob:",
  "https://*.firebaseio.com",
  "https://*.googleapis.com"
];

export const helmetConfig = {
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'", ...cspDomains],
      scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'", ...cspDomains],
      scriptSrcAttr: ["'unsafe-inline'"],
      styleSrc: ["'self'", "'unsafe-inline'", ...cspDomains],
      styleSrcAttr: ["'unsafe-inline'"],
      imgSrc: ["'self'", "data:", "blob:", ...cspDomains],
      fontSrc: ["'self'", "data:", ...cspDomains],
      connectSrc: ["'self'", "https://api.ipquery.io", ...cspDomains],
      frameSrc: ["'self'", ...cspDomains],
      mediaSrc: ["'self'", ...cspDomains],
      objectSrc: ["'none'"],
      workerSrc: ["'self'", "blob:"],
      manifestSrc: ["'self'", ...cspDomains],
      prefetchSrc: ["'self'", ...cspDomains],
      formAction: ["'self'", ...cspDomains],
      frameAncestors: ["'self'", ...cspDomains],
      baseUri: ["'self'"],
      upgradeInsecureRequests: [],
    },
    reportOnly: false,
  },
  crossOriginEmbedderPolicy: false,
  crossOriginOpenerPolicy: { policy: "unsafe-none" },
  crossOriginResourcePolicy: { policy: "cross-origin" },
  originAgentCluster: false,
  dnsPrefetchControl: { allow: true },
  frameguard: { action: 'sameorigin' },
  hsts: {
    maxAge: 31536000,
    includeSubDomains: true,
    preload: true
  },
  ieNoOpen: true,
  noSniff: true,
  permittedCrossDomainPolicies: { permittedPolicies: 'all' },
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },
  xssFilter: true
};
