# fly.toml app configuration file generated for masitaprexv2 on 2026-05-02T16:31:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'masitaprexv2'
primary_region = 'iad'

[build]

[env]
  FIREBASE_CLIENT_EMAIL = ''
  FIREBASE_PRIVATE_KEY = ''
  FIREBASE_PROJECT_ID = ''
  FIREBASE_SERVICE_ACCOUNT = ''
  HOST_URL = 'https://www.masitaprex.com'
  RECAPTCHA_CLAVE_SECRETA = ''
  RESEND_API_KEY = ''
  SLACK_WEBHOOK_URL = ''
  TELEGRAM_BOT_TOKEN = ''

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  # Kill timeout de 10 minutos para dar margen antes del apagado total
  kill_signal = 'SIGTERM'
  kill_timeout = '600s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
