# fly.toml app configuration file for masitaprexv2
app = 'masitaprexv2'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  # 'stop' apaga la máquina por completo cuando no hay tráfico
  auto_stop_machines = 'stop'
  auto_start_machines = true
  # Cambiado a 0 para que la máquina PUEDA apagarse si no hay nadie
  min_machines_running = 0
  processes = ['app']
  
  # Tiempo de espera para el auto-stop (300 segundos = 5 minutos)
  [http_service.termination]
    grace_period = "5s"

[http_service.concurrency]
  type = 'requests'
  soft_limit = 20
  hard_limit = 25

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
